sensitiveCodepaths:
  # Files only allowed authors can modify
  # - 'app.js'
  # - 'requirements.txt'
allowedAuthors:
  usernames:
    # GitHub username
    # - 'jordan-dr'
notificationList:
  # GitHub username or team name
  - '@DryRunSec/security'
  # - '@john-doe'
codePolicies:
  - title: "API Auth Bypass"
    question: "Does this change bypass authentication on any API endpoints?"
  - title: "Hardcoded Credentials"
    question: "Does this change add hardcoded credentials?"
