sensitiveCodepaths:
  # Files only allowed authors can modify
  # - 'app.js'
  # - 'requirements.txt'
allowedAuthors:
  usernames:
    # GitHub username
    # - 'jordan-dr'
notificationList:
  # GitHub username or team name
  - '@DryRunSec/security'
  # - '@john-doe'
codePolicies:
  - title: "Unrestricted GraphQL Query"
    question: "An Unrestricted GraphQL Query refers to a GraphQL query that is not subject to any restrictions or limitations on its complexity, depth, or the amount of data it can retrieve. Does this change allow users to submit unrestricted GraphQL queries?"

